---
- name: Create Database configmap
  community.kubernetes.k8s:
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-db-configmap'
        namespace: '{{ ansible_operator_meta.namespace }}'
      data:
        database: employee_db
        host: mysql

- name: Create Database secret
  community.kubernetes.k8s:
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-db-secret'
        namespace: '{{ ansible_operator_meta.namespace }}'
      data:
        root-username: cm9vdA==
        root-password: cm9vdA==